### ISSUE TITLE
There are a lot of compiling errors

### ISSUE THREAD

**Issue by rosedge** [CarolVerilog/CarolEngine#1]
There are 48 errors in the error list, most of the errors are similar.
1. error C1083: Cannot open include file: 'assimp/scene.h': No such file or directory.
2. Variable 'ResourceDescriptorHeap' is not declared.	
3. No overload for method 'InterlockedOr' takes 2 arguments.  \carol-engine\carol_renderer\shader\include\cull.hlsli	93
4. No overload for method 'InterlockedAnd' takes 2 arguments.	\carol-engine\carol_renderer\shader\include\cull.hlsli	99
5. identifier "aiNode" is undefined	carol_renderer  \carol-engine\carol_renderer\include\scene\assimp.h	30	
6. identifier "aiScene" is undefined	carol_renderer	 \carol-engine\carol_renderer\include\scene\assimp.h	32	
7. identifier "aiMesh" is undefined	carol_renderer	 \carol-engine\carol_renderer\include\scene\assimp.h	34
8. identifier "aiString" is undefined	carol_renderer	\carol-engine\carol_renderer\include\scene\assimp.h	54
9. identifier "aiTextureType" is undefined carol_renderer \carol-engine\carol_renderer\include\scene\assimp.h	55

**Comment by tsssni** [comment]
没找到依赖库和没有设置include路径导致的，vs配置有点麻烦，我会写一份cmake传到仓库里，这之前你可以自己尝试解决一下。注意不要让vs去编译shader，仓库里有写编译shader的powershell脚本。

**Comment by tsssni** [comment]
你好，cmake配置已传到仓库中，README中加入了build教程

**Comment by rosedge** [comment]
这个版本已经可以正常编译了，但是当运行时在D3DGetDebugInterface时候会报错。
![image](https://github.com/tsssni/carol-engine/assets/8540757/03efaf5f-9676-4f6a-b882-456b7fe7e427)
本地环境我已经检查过了，graphics tools都是有的。我的环境是vs2022，windows10，rtx2060 driver最新的。如果关掉验证层，加载root_signature.dxil shader时候也会报错。
![image](https://github.com/tsssni/carol-engine/assets/8540757/4c1cf421-ca6a-4a4d-84e7-5c1c7e967965)
可能是我的环境还是有问题，不知道你本地的工程能不能正常运行

**Comment by tsssni** [comment]
试一下nvidia control panel 打开开发者选项 打开性能计数器

**Comment by tsssni** [comment]
本地我已经都验证过了 我是直接powershell构建运行的，现在运行在4070，一年前开发这个项目的时候跑的也是2060。

**Comment by rosedge** [comment]
我已经打开了，还是报同样的错误。我还有一个RTX3080的卡，晚上我试试看，理论上和显卡应该没有关系的。

**Comment by tsssni** [comment]
可能我用的ID3D12Debug5类你的windows sdk不支持？我4070和2060的机器都是win11 sdk

**Comment by rosedge** [comment]
你说的还真有道理，我查了下，有最低版本要求，我的windows10支持到debug2。我改完后，debugLayer初始化是正常通过了。后面加载oot_signature.dxil 还是报错，是读进来的是相对路径，没有做转换，是有什么配置吗

**Comment by tsssni** [comment]
在控制台cd到${project_dir}/build/bin中手动执行carol-engine.exe 因为相对路径的关系现在只能这样运行

**Comment by tsssni** [comment]
我用vscode cmake插件是可以直接在editor里执行的，vs暂时不做支持了，你得自己摸索一下

**Comment by rosedge** [comment]
行，我先这样玩一玩，搞明白了，我就知道怎么改了。由于你的代码是基于win11 SDK写的，可能在win10上运行时还有很多错误，不过我可以自己尝试改了。

**Comment by rosedge** [comment]
这个版本的代码确实不兼容win10设备，配置完适合的shader路径后，初始化资源时，在堆上CreatePlacedResource时候会失败。
![image](https://github.com/tsssni/carol-engine/assets/8540757/3e52a9db-e8e7-4bd2-95cf-6ed7ba7b2e5f)
